### ISSUE TITLE
getting error:Which version of tensorflow and keras should be be used?

### ISSUE THREAD

**Issue by Pooja-Palod** [zygmuntz/pointer-networks-experiments#3]
Using TensorFlow backend.
building model...
2017-10-05 22:49:42.913503: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-05 22:49:42.913593: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-05 22:49:42.913613: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "train.py", line 54, in <module>
    encoder = LSTM(output_dim = hidden_size, return_sequences = True, name="encoder")(main_input)
  File "/home/snorkel/miniconda2/envs/py2Env/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/home/snorkel/miniconda2/envs/py2Env/lib/python2.7/site-packages/keras/layers/recurrent.py", line 710, in build
    self.W = K.concatenate([self.W_i, self.W_f, self.W_c, self.W_o])
  File "/home/snorkel/miniconda2/envs/py2Env/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 716, in concatenate
    return tf.concat(axis, [to_dense(x) for x in tensors])
  File "/home/snorkel/miniconda2/envs/py2Env/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1061, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/snorkel/miniconda2/envs/py2Env/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 611, in convert_to_tensor
    as_ref=False)
  File "/home/snorkel/miniconda2/envs/py2Env/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/snorkel/miniconda2/envs/py2Env/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/snorkel/miniconda2/envs/py2Env/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/snorkel/miniconda2/envs/py2Env/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/snorkel/miniconda2/envs/py2Env/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got <tf.Variable 'encoder_W_i:0' shape=(1, 64) dtype=float32_ref> of type 'Variable' instead.

**Comment by zygmuntz** [comment]
All I know is that the master branch users Keras 1, then there's keras-2.0 branch. For issues like this, maybe try the source repository: https://github.com/keon/pointer-networks
